DROP TABLE IF EXISTS alumno;
DROP TABLE IF EXISTS materia;

CREATE TABLE materia (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL
);

CREATE TABLE alumno (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    apellido VARCHAR(255) NOT NULL,
    materia_id BIGINT,
    FOREIGN KEY (materia_id) REFERENCES materia(id)
);